### ISSUE TITLE
(Not high priority but easily fixable) - Mantella blocks loading of 2.0 XVASynth voices

### ISSUE THREAD

**Issue by teddybear082** [art-from-the-machine/Mantella#124]
This came up because of a user wanting to utilize a 2.0 Witcher voice (Triss) for an NPC in Mantella.  User reported that the voice would not work.

On review,  tts.py's change_voice function at line 298 hard codes the version of the voice as 3.0:

 ```
model_change = {
            'outputs': None,
            'version': '3.0',
            'model': voice_path, 
            'modelType': self.model_type,
            'base_lang': self.language, 
            'pluginsContext': '{}',
        }
```

Instead, the version should likely be treated the same as base_speaker_emb and modelType in the script, with something like:

`voice_version = voice_model_json.get('version')`

Overall this is not a high priority because a limited number of users are going to want a non-skyrim model for a voice and even more limited will want to use a pre-3.0 voice but still technically a "bug" as it was not likely intentional for Mantella to exclude support for pre-3.0 models.

**Comment by Pendrokar** [comment]
Could not recreate the issue. xVASynth ignores the version number. Since the whole character bios structure is being overturned, this is not a good time to add support for non-Skyrim models as that will come.

The current workaround is to either move/copy/(make symlinks) of the other models, `sk_maledunmermorrowind.json` example:
```json
{
    "version": "2.1",
    "modelVersion": "2.0",
    "modelType": "FastPitch1.1",
    "author": "DanRuta",
    "lang": "en",
    "games": [
        {
            "gameId": "skyrim",
            "voiceId": "sk_maledunmermorrowind",
            "variant": "Default",
            "voiceName": "MaleDunmerMorrowind",
            "resemblyzer": [
...
```

On making symlinks, if you do not wish to copy the `.pt` files:
https://www.howtogeek.com/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/

**Comment by Pendrokar** [comment]
Relates to #71

**Comment by teddybear082** [comment]
Ok the user must have had some other issue so closing this.
